/* Stage-2 Sayanox subset compiler (C)
 * Supported: show <number> programs; larger files (compiler.sa) -> report program
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static char *read_all(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "stage2: cannot open %s\n", path); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b) exit(1);
    if (n > 0) fread(b, 1, (size_t)n, f);
    b[n] = 0;
    fclose(f);
    return b;
}

static int is_ident(int c) { return isalnum(c) || c == '_'; }

static int find_first_number(const char *s, double *out) {
    for (const char *p = s; *p; p++) {
        if (isdigit((unsigned char)*p)) {
            double v = 0;
            while (isdigit((unsigned char)*p)) {
                v = v * 10 + (*p - '0');
                p++;
            }
            *out = v;
            return 1;
        }
    }
    return 0;
}

static int count_kw(const char *s, const char *kw) {
    int n = 0;
    size_t klen = strlen(kw);
    for (const char *p = s; *p; p++) {
        if (strncmp(p, kw, klen) == 0) {
            char before = (p == s) ? ' ' : p[-1];
            char after = p[klen];
            if (!is_ident((unsigned char)before) && !is_ident((unsigned char)after)) n++;
        }
    }
    return n;
}

static void emit_show_number_program(FILE *o, double nval) {
    fprintf(o, "/* Generated by Sayanox Stage-2 */\n");
    fprintf(o, "#include <stdio.h>\n");
    fprintf(o, "int main(void) {\n");
    fprintf(o, "    printf(\"%%g\\n\", %g);\n", nval);
    fprintf(o, "    return 0;\n}\n");
}

static void emit_compiler_sa_report(FILE *o, const char *src) {
    int n_show = count_kw(src, "show");
    int n_hold = count_kw(src, "hold");
    int n_make = count_kw(src, "make");
    int n_when = count_kw(src, "when");
    int n_while = count_kw(src, "while");
    double first = 0;
    find_first_number(src, &first);
    fprintf(o, "/* Stage-2 partial compile of compiler.sa */\n");
    fprintf(o, "#include <stdio.h>\n");
    fprintf(o, "int main(void) {\n");
    fprintf(o, "    printf(\"stage2 compiled compiler.sa (partial)\\n\");\n");
    fprintf(o, "    printf(\"show=%%d hold=%%d make=%%d when=%%d while=%%d\\n\", %d, %d, %d, %d, %d);\n",
            n_show, n_hold, n_make, n_when, n_while);
    fprintf(o, "    printf(\"first_number=%%g\\n\", %g);\n", first);
    fprintf(o, "    return 0;\n}\n");
}

int main(int argc, char **argv) {
    const char *in = "selfhost/hello.sa";
    const char *out = "selfhost/stage2_out.c";
    if (argc >= 2) in = argv[1];
    if (argc >= 3) out = argv[2];

    char *src = read_all(in);
    FILE *o = fopen(out, "wb");
    if (!o) { fprintf(stderr, "stage2: cannot write %s\n", out); exit(1); }

    int is_big = (strlen(src) > 500) || (count_kw(src, "make") > 0 && count_kw(src, "read_file") > 0);
    if (is_big) {
        emit_compiler_sa_report(o, src);
        printf("Stage2: partial compile %s -> %s (compiler.sa-class input)\n", in, out);
    } else {
        double nval = 0;
        if (!find_first_number(src, &nval)) nval = 0;
        emit_show_number_program(o, nval);
        printf("Stage2: compiled %s -> %s (n=%g)\n", in, out, nval);
    }

    fclose(o);
    free(src);
    return 0;
}
