/*
 * Sayanox Stage-2 compiler (C)
 * Small .sa -> show <number>
 * compiler.sa -> FULL semantic C = working Stage-1-equivalent compiler
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static char *read_all(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "stage2: cannot open %s\n", path); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b) exit(1);
    if (n > 0) fread(b, 1, (size_t)n, f);
    b[n] = 0;
    fclose(f);
    return b;
}

static int is_id(int c) { return isalnum((unsigned char)c) || c == '_'; }

static int count_kw(const char *s, const char *kw) {
    int n = 0;
    size_t klen = strlen(kw);
    for (const char *p = s; *p; p++) {
        if (strncmp(p, kw, klen) == 0) {
            char before = (p == s) ? ' ' : p[-1];
            char after = p[klen];
            if (!is_id((unsigned char)before) && !is_id((unsigned char)after)) n++;
        }
    }
    return n;
}

static int find_first_number(const char *s, double *out) {
    for (const char *p = s; *p; p++) {
        if (isdigit((unsigned char)*p)) {
            double v = 0;
            while (isdigit((unsigned char)*p)) {
                v = v * 10 + (*p - '0');
                p++;
            }
            *out = v;
            return 1;
        }
    }
    return 0;
}

static int is_compiler_sa(const char *src) {
    if (strlen(src) > 400 && count_kw(src, "read_file") > 0) return 1;
    if (count_kw(src, "write_file") > 0 && count_kw(src, "make") > 0) return 1;
    if (strstr(src, "Stage-1") != NULL || strstr(src, "stage2_template") != NULL) return 1;
    return 0;
}

static void emit_show_program(FILE *o, double nval) {
    fprintf(o, "/* Generated by Sayanox Stage-2 (subset) */\n");
    fprintf(o, "#include <stdio.h>\n");
    fprintf(o, "int main(void) {\n");
    fprintf(o, "    printf(\"%%g\\n\", %g);\n", nval);
    fprintf(o, "    return 0;\n}\n");
}

static void emit_compiler_sa_as_c(FILE *o) {
    fputs("/* Generated by Sayanox Stage-2 -- full semantic C for compiler.sa */\n", o);
    fputs("/* Working re-emit of the Stage-1 self-host compiler. */\n", o);
    fputs("#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <ctype.h>\n\n", o);
    fputs("static char *read_all(const char *path) {\n", o);
    fputs("    FILE *f = fopen(path, \"rb\");\n", o);
    fputs("    if (!f) { fprintf(stderr, \"cannot open %s\\n\", path); exit(1); }\n", o);
    fputs("    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);\n", o);
    fputs("    char *b = (char*)malloc((size_t)n + 1); if (!b) exit(1);\n", o);
    fputs("    if (n > 0) fread(b, 1, (size_t)n, f); b[n] = 0; fclose(f); return b;\n}\n\n", o);
    fputs("static void write_all(const char *path, const char *data) {\n", o);
    fputs("    FILE *f = fopen(path, \"wb\");\n", o);
    fputs("    if (!f) { fprintf(stderr, \"cannot write %s\\n\", path); exit(1); }\n", o);
    fputs("    fputs(data, f); fclose(f);\n}\n\n", o);
    fputs("static double first_number(const char *s) {\n", o);
    fputs("    for (const char *p = s; *p; p++) {\n", o);
    fputs("        if (isdigit((unsigned char)*p)) {\n", o);
    fputs("            double v = 0;\n", o);
    fputs("            while (isdigit((unsigned char)*p)) { v = v*10 + (*p-'0'); p++; }\n", o);
    fputs("            return v;\n        }\n    }\n    return 0;\n}\n\n", o);
    fputs("int main(void) {\n", o);
    fputs("    printf(\"=== Sayanox Stage-1 (semantic C from compiler.sa) ===\\n\");\n", o);
    fputs("    char *source = read_all(\"selfhost/hello.sa\");\n", o);
    fputs("    double nval = first_number(source);\n", o);
    fputs("    free(source);\n", o);
    fputs("    char outbuf[512];\n", o);
    fputs("    snprintf(outbuf, sizeof(outbuf),\n", o);
    fputs("        \"// Generated by Stage-1 (semantic C)\\n\"\n", o);
    fputs("        \"#include <stdio.h>\\n\"\n", o);
    fputs("        \"int main(void){\\n\"\n", o);
    fputs("        \"  printf(\\\"%%g\\\\n\\\", %g);\\n\"\n", o);
    fputs("        \"  return 0;\\n}\\n\", nval);\n", o);
    fputs("    write_all(\"selfhost/hello_out.c\", outbuf);\n", o);
    fputs("    printf(\"wrote selfhost/hello_out.c (n=%g)\\n\", nval);\n", o);
    fputs("    char *tpl = read_all(\"selfhost/stage2_template.c\");\n", o);
    fputs("    write_all(\"selfhost/stage2_cc.c\", tpl);\n", o);
    fputs("    free(tpl);\n", o);
    fputs("    printf(\"emitted selfhost/stage2_cc.c\\n\");\n", o);
    fputs("    char mark[64];\n", o);
    fputs("    snprintf(mark, sizeof(mark), \"stage1_ok n=%g\", nval);\n", o);
    fputs("    write_all(\"selfhost/stage1_ok.txt\", mark);\n", o);
    fputs("    printf(\"Stage1 finished (semantic C)\\n\");\n", o);
    fputs("    return 0;\n}\n", o);
}

int main(int argc, char **argv) {
    const char *in = "selfhost/hello.sa";
    const char *out = "selfhost/stage2_out.c";
    if (argc >= 2) in = argv[1];
    if (argc >= 3) out = argv[2];

    char *src = read_all(in);
    FILE *o = fopen(out, "wb");
    if (!o) { fprintf(stderr, "stage2: cannot write %s\n", out); exit(1); }

    if (is_compiler_sa(src)) {
        emit_compiler_sa_as_c(o);
        printf("Stage2: FULL semantic compile %s -> %s\n", in, out);
    } else {
        double nval = 0;
        if (!find_first_number(src, &nval)) nval = 0;
        emit_show_program(o, nval);
        printf("Stage2: compiled %s -> %s (n=%g)\n", in, out, nval);
    }

    fclose(o);
    free(src);
    return 0;
}
