//! C Code Generator for Sayanox
//! Builtins: len, push, concat, read_file, write_file, str

use crate::ast::*;
use std::collections::HashMap;

pub struct Codegen {
    functions: HashMap<String, (Vec<String>, Vec<Stmt>)>,
    structs: HashMap<String, Vec<String>>,
    output: String,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            functions: HashMap::new(),
            structs: HashMap::new(),
            output: String::new(),
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.output.clear();
        self.functions.clear();
        self.structs.clear();

        self.output.push_str("// Generated by Sayanox Compiler\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdlib.h>\n");
        self.output.push_str("#include <string.h>\n\n");
        self.output.push_str(
            "typedef struct { double *data; int len; int cap; } SxList;\n\
static SxList sx_list_new(void) { SxList l; l.data=NULL; l.len=0; l.cap=0; return l; }\n\
static void sx_list_push(SxList *l, double v) {\n\
  if (l->len >= l->cap) {\n\
    int ncap = l->cap==0 ? 8 : l->cap*2;\n\
    double *nd = (double*)realloc(l->data, sizeof(double)*ncap);\n\
    if (!nd) { fprintf(stderr,\"Sayanox: out of memory\\n\"); exit(1); }\n\
    l->data = nd; l->cap = ncap;\n\
  }\n\
  l->data[l->len++] = v;\n\
}\n\
static double sx_list_get(SxList *l, int i) {\n\
  if (i<0 || i>=l->len) { fprintf(stderr,\"Sayanox: index out of bounds\\n\"); exit(1); }\n\
  return l->data[i];\n\
}\n\
static int sx_list_len(SxList *l) { return l->len; }\n\
static char *sx_concat(const char *a, const char *b) {\n\
  size_t la=strlen(a), lb=strlen(b);\n\
  char *r=(char*)malloc(la+lb+1);\n\
  if (!r) { fprintf(stderr,\"Sayanox: out of memory\\n\"); exit(1); }\n\
  memcpy(r,a,la); memcpy(r+la,b,lb); r[la+lb]=0; return r;\n\
}\n\
static char *sx_read_file(const char *path) {\n\
  FILE *f = fopen(path, \"rb\");\n\
  if (!f) { fprintf(stderr,\"Sayanox: cannot open %s\\n\", path); exit(1); }\n\
  fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);\n\
  char *buf = (char*)malloc((size_t)n + 1);\n\
  if (!buf) { fprintf(stderr,\"Sayanox: out of memory\\n\"); exit(1); }\n\
  fread(buf, 1, (size_t)n, f); buf[n]=0; fclose(f); return buf;\n\
}\n\
static double sx_write_file(const char *path, const char *data) {\n\
  FILE *f = fopen(path, \"wb\");\n\
  if (!f) { fprintf(stderr,\"Sayanox: cannot write %s\\n\", path); exit(1); }\n\
  fputs(data, f); fclose(f); return 0.0;\n\
}\n\
static char *sx_str(double n) {\n\
  char *buf = (char*)malloc(64);\n\
  if (!buf) { fprintf(stderr,\"Sayanox: out of memory\\n\"); exit(1); }\n\
  snprintf(buf, 64, \"%g\", n);\n\
  return buf;\n\
}\n\n",
        );

        for stmt in &program.statements {
            match stmt {
                Stmt::Make { name, params, body } => {
                    self.functions.insert(name.clone(), (params.clone(), body.clone()));
                }
                Stmt::StructDef { name, fields } => {
                    self.structs.insert(name.clone(), fields.clone());
                }
                _ => {}
            }
        }

        for (name, fields) in &self.structs {
            self.output.push_str(&format!("typedef struct {{\n"));
            for f in fields {
                self.output.push_str(&format!("    double {};\n", f));
            }
            self.output.push_str(&format!("}} {};\n\n", name));
        }

        let functions: Vec<_> = self
            .functions
            .iter()
            .map(|(n, (p, b))| (n.clone(), p.clone(), b.clone()))
            .collect();
        for (name, params, body) in functions {
            self.gen_function(&name, &params, &body);
        }

        self.output.push_str("int main() {\n");
        for stmt in &program.statements {
            if !matches!(stmt, Stmt::Make { .. } | Stmt::StructDef { .. }) {
                self.gen_stmt(stmt, 1);
            }
        }
        self.output.push_str("    return 0;\n}\n");
        self.output.clone()
    }

    fn gen_function(&mut self, name: &str, params: &[String], body: &[Stmt]) {
        let c_name = format!("sx_{}", name);
        self.output.push_str(&format!("double {}(", c_name));
        for (i, p) in params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            self.output.push_str(&format!("double {}", p));
        }
        self.output.push_str(") {\n");
        for stmt in body {
            self.gen_stmt(stmt, 1);
        }
        self.output.push_str("    return 0.0;\n}\n\n");
    }

    fn gen_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let ind = "    ".repeat(indent);
        match stmt {
            Stmt::Show(expr) => match expr {
                Expr::String(s) => self.output.push_str(&format!(
                    "{}printf(\"%s\\n\", \"{}\");\n", ind, escape_c(s)
                )),
                Expr::Number(n) => self
                    .output
                    .push_str(&format!("{}printf(\"%g\\n\", {});\n", ind, n)),
                Expr::Call { name, .. }
                    if name == "read_file" || name == "concat" || name == "str" =>
                {
                    let code = self.gen_expr(expr);
                    self.output
                        .push_str(&format!("{}printf(\"%s\\n\", {});\n", ind, code));
                }
                Expr::Ident(_) => {
                    let code = self.gen_expr(expr);
                    self.output
                        .push_str(&format!("{}printf(\"%s\\n\", {});\n", ind, code));
                }
                _ => {
                    let code = self.gen_expr(expr);
                    self.output
                        .push_str(&format!("{}printf(\"%g\\n\", {});\n", ind, code));
                }
            },
            Stmt::Hold { name, value } => match value {
                Expr::String(s) => self.output.push_str(&format!(
                    "{}const char* {} = \"{}\";\n", ind, name, escape_c(s)
                )),
                Expr::Array(elements) if elements.is_empty() => {
                    self.output
                        .push_str(&format!("{}SxList {} = sx_list_new();\n", ind, name));
                }
                Expr::Array(elements) => {
                    let len = elements.len();
                    self.output
                        .push_str(&format!("{}double {}[{}] = {{", ind, name, len));
                    for (i, e) in elements.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        self.output.push_str(&self.gen_expr(e));
                    }
                    self.output.push_str("};\n");
                }
                Expr::StructLit { name: sname, fields } => {
                    self.output
                        .push_str(&format!("{}{} {} = {{", ind, sname, name));
                    for (i, (_, val)) in fields.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        self.output.push_str(&self.gen_expr(val));
                    }
                    self.output.push_str("};\n");
                }
                _ => {
                    let code = self.gen_expr(value);
                    if matches!(
                        value,
                        Expr::Call { name: n, .. }
                            if n == "concat" || n == "read_file" || n == "str"
                    ) {
                        self.output
                            .push_str(&format!("{}char* {} = {};\n", ind, name, code));
                    } else {
                        self.output
                            .push_str(&format!("{}double {} = {};\n", ind, name, code));
                    }
                }
            },
            Stmt::Give(expr) => {
                let code = self.gen_expr(expr);
                self.output.push_str(&format!("{}return {};\n", ind, code));
            }
            Stmt::When {
                condition,
                then_body,
                otherwise_body,
            } => {
                let cond = self.gen_expr(condition);
                self.output.push_str(&format!("{}if ({}) {{\n", ind, cond));
                for s in then_body {
                    self.gen_stmt(s, indent + 1);
                }
                self.output.push_str(&format!("{}}}\n", ind));
                if let Some(else_body) = otherwise_body {
                    self.output.push_str(&format!("{}else {{\n", ind));
                    for s in else_body {
                        self.gen_stmt(s, indent + 1);
                    }
                    self.output.push_str(&format!("{}}}\n", ind));
                }
            }
            Stmt::While { condition, body } => {
                let cond = self.gen_expr(condition);
                self.output.push_str(&format!("{}while ({}) {{\n", ind, cond));
                for s in body {
                    self.gen_stmt(s, indent + 1);
                }
                self.output.push_str(&format!("{}}}\n", ind));
            }
            Stmt::StructDef { .. } | Stmt::Make { .. } => {}
            Stmt::Expr(expr) => {
                let code = self.gen_expr(expr);
                self.output.push_str(&format!("{}{};\n", ind, code));
            }
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => format!("{}", n),
            Expr::String(s) => format!("\"{}\"", escape_c(s)),
            Expr::Ident(name) => name.clone(),
            Expr::Binary { left, op, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Gt => ">",
                    BinOp::Lt => "<",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Gte => ">=",
                    BinOp::Lte => "<=",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Call { name, args } => {
                if name == "len" && args.len() == 1 {
                    match &args[0] {
                        Expr::String(s) => format!("{}", s.chars().count()),
                        Expr::Array(elements) => format!("{}", elements.len()),
                        Expr::Ident(id) => format!("((double)sx_list_len(&{}))", id),
                        other => format!("((double)strlen({}))", self.gen_expr(other)),
                    }
                } else if name == "push" && args.len() == 2 {
                    format!(
                        "(sx_list_push(&{}, {}), 0.0)",
                        self.gen_expr(&args[0]),
                        self.gen_expr(&args[1])
                    )
                } else if name == "concat" && args.len() == 2 {
                    format!(
                        "sx_concat({}, {})",
                        self.gen_expr(&args[0]),
                        self.gen_expr(&args[1])
                    )
                } else if name == "read_file" && args.len() == 1 {
                    format!("sx_read_file({})", self.gen_expr(&args[0]))
                } else if name == "write_file" && args.len() == 2 {
                    format!(
                        "sx_write_file({}, {})",
                        self.gen_expr(&args[0]),
                        self.gen_expr(&args[1])
                    )
                } else if name == "str" && args.len() == 1 {
                    format!("sx_str({})", self.gen_expr(&args[0]))
                } else {
                    let args_code: Vec<String> =
                        args.iter().map(|a| self.gen_expr(a)).collect();
                    format!("sx_{}({})", name, args_code.join(", "))
                }
            }
            Expr::Array(elements) => {
                if elements.is_empty() {
                    "sx_list_new()".to_string()
                } else {
                    let elems: Vec<String> =
                        elements.iter().map(|e| self.gen_expr(e)).collect();
                    format!("{{{}}}", elems.join(", "))
                }
            }
            Expr::Index { array, index } => match array.as_ref() {
                Expr::Ident(name) => {
                    format!("sx_list_get(&{}, (int)({}))", name, self.gen_expr(index))
                }
                _ => format!(
                    "((int)({}[(int)({})]))",
                    self.gen_expr(array),
                    self.gen_expr(index)
                ),
            },
            Expr::StructLit { name, fields } => {
                let vals: Vec<String> =
                    fields.iter().map(|(_, v)| self.gen_expr(v)).collect();
                format!("({}){{{}}}", name, vals.join(", "))
            }
            Expr::Field { object, field } => {
                format!("{}.{}", self.gen_expr(object), field)
            }
        }
    }
}

fn escape_c(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}
