//! C Code Generator for Sayanox
//! Translates Sayanox AST into readable C code.

use crate::ast::*;
use std::collections::HashMap;

pub struct Codegen {
    functions: HashMap<String, (Vec<String>, Vec<Stmt>)>,
    structs: HashMap<String, Vec<String>>,
    output: String,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            functions: HashMap::new(),
            structs: HashMap::new(),
            output: String::new(),
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.output.clear();
        self.functions.clear();
        self.structs.clear();

        // Header
        self.output.push_str("// Generated by Sayanox Compiler\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdlib.h>\n");
        self.output.push_str("#include <string.h>\n\n");

        // Collect functions and structs
        for stmt in &program.statements {
            match stmt {
                Stmt::Make { name, params, body } => {
                    self.functions
                        .insert(name.clone(), (params.clone(), body.clone()));
                }
                Stmt::StructDef { name, fields } => {
                    self.structs.insert(name.clone(), fields.clone());
                }
                _ => {}
            }
        }

        // Emit struct definitions
        for (name, fields) in &self.structs {
            self.output.push_str(&format!("typedef struct {{\n"));
            for f in fields {
                self.output.push_str(&format!("    double {};\n", f));
            }
            self.output.push_str(&format!("}} {};\n\n", name));
        }

        // Emit function definitions
        let functions: Vec<_> = self
            .functions
            .iter()
            .map(|(n, (p, b))| (n.clone(), p.clone(), b.clone()))
            .collect();
        for (name, params, body) in functions {
            self.gen_function(&name, &params, &body);
        }

        // Main
        self.output.push_str("int main() {\n");
        for stmt in &program.statements {
            if !matches!(stmt, Stmt::Make { .. } | Stmt::StructDef { .. }) {
                self.gen_stmt(stmt, 1);
            }
        }
        self.output.push_str("    return 0;\n");
        self.output.push_str("}\n");

        self.output.clone()
    }

    fn gen_function(&mut self, name: &str, params: &[String], body: &[Stmt]) {
        let c_name = format!("sx_{}", name);
        self.output.push_str(&format!("double {}(", c_name));
        for (i, p) in params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            self.output.push_str(&format!("double {}", p));
        }
        self.output.push_str(") {\n");
        for stmt in body {
            self.gen_stmt(stmt, 1);
        }
        self.output.push_str("    return 0.0;\n");
        self.output.push_str("}\n\n");
    }

    fn gen_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let ind = "    ".repeat(indent);
        match stmt {
            Stmt::Show(expr) => {
                match expr {
                    Expr::String(s) => {
                        self.output.push_str(&format!(
                            "{}printf(\"%s\\n\", \"{}\");\n",
                            ind,
                            escape_c(s)
                        ));
                    }
                    Expr::Number(n) => {
                        self.output
                            .push_str(&format!("{}printf(\"%g\\n\", {});\n", ind, n));
                    }
                    _ => {
                        let code = self.gen_expr(expr);
                        self.output
                            .push_str(&format!("{}printf(\"%g\\n\", {});\n", ind, code));
                    }
                }
            }
            Stmt::Hold { name, value } => {
                match value {
                    Expr::String(s) => {
                        self.output.push_str(&format!(
                            "{}const char* {} = \"{}\";\n",
                            ind,
                            name,
                            escape_c(s)
                        ));
                    }
                    Expr::Array(elements) => {
                        let len = elements.len();
                        self.output
                            .push_str(&format!("{}double {}[{}] = {{", ind, name, len));
                        for (i, e) in elements.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.output.push_str(&self.gen_expr(e));
                        }
                        self.output.push_str("};\n");
                    }
                    Expr::StructLit { name: sname, fields } => {
                        self.output
                            .push_str(&format!("{}{} {} = {{", ind, sname, name));
                        for (i, (_, val)) in fields.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.output.push_str(&self.gen_expr(val));
                        }
                        self.output.push_str("};\n");
                    }
                    _ => {
                        let code = self.gen_expr(value);
                        self.output
                            .push_str(&format!("{}double {} = {};\n", ind, name, code));
                    }
                }
            }
            Stmt::Give(expr) => {
                let code = self.gen_expr(expr);
                self.output
                    .push_str(&format!("{}return {};\n", ind, code));
            }
            Stmt::When {
                condition,
                then_body,
                otherwise_body,
            } => {
                let cond = self.gen_expr(condition);
                self.output
                    .push_str(&format!("{}if ({}) {{\n", ind, cond));
                for s in then_body {
                    self.gen_stmt(s, indent + 1);
                }
                self.output.push_str(&format!("{}}}\n", ind));
                if let Some(else_body) = otherwise_body {
                    self.output.push_str(&format!("{}else {{\n", ind));
                    for s in else_body {
                        self.gen_stmt(s, indent + 1);
                    }
                    self.output.push_str(&format!("{}}}\n", ind));
                }
            }
            Stmt::While { condition, body } => {
                let cond = self.gen_expr(condition);
                self.output
                    .push_str(&format!("{}while ({}) {{\n", ind, cond));
                for s in body {
                    self.gen_stmt(s, indent + 1);
                }
                self.output.push_str(&format!("{}}}\n", ind));
            }
            Stmt::StructDef { .. } | Stmt::Make { .. } => {}
            Stmt::Expr(expr) => {
                let code = self.gen_expr(expr);
                self.output.push_str(&format!("{}{};\n", ind, code));
            }
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => format!("{}", n),
            Expr::String(s) => format!("\"{}\"", escape_c(s)),
            Expr::Ident(name) => name.clone(),
            Expr::Binary { left, op, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Gt => ">",
                    BinOp::Lt => "<",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Gte => ">=",
                    BinOp::Lte => "<=",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Call { name, args } => {
                let args_code: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                format!("sx_{}({})", name, args_code.join(", "))
            }
            Expr::Array(elements) => {
                let elems: Vec<String> = elements.iter().map(|e| self.gen_expr(e)).collect();
                format!("{{{}}}", elems.join(", "))
            }
            Expr::Index { array, index } => {
                format!("{}[(int)({})]", self.gen_expr(array), self.gen_expr(index))
            }
            Expr::StructLit { name, fields } => {
                let vals: Vec<String> = fields.iter().map(|(_, v)| self.gen_expr(v)).collect();
                format!("({}){{{}}}", name, vals.join(", "))
            }
            Expr::Field { object, field } => {
                format!("{}.{}", self.gen_expr(object), field)
            }
        }
    }
}

fn escape_c(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}
