//! C code generator for Sayanox.
//! The generated runtime contains the small, dependency-free standard library.

use crate::ast::*;
use crate::stdlib;
use std::collections::HashMap;

pub struct Codegen { functions: HashMap<String, (Vec<String>, Vec<Stmt>)>, structs: HashMap<String, Vec<String>>, output: String }

impl Codegen {
    pub fn new() -> Self { Self { functions: HashMap::new(), structs: HashMap::new(), output: String::new() } }

    pub fn generate(&mut self, program: &Program) -> String {
        self.output.clear(); self.functions.clear(); self.structs.clear();
        self.output.push_str("// Generated by Sayanox Compiler\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <ctype.h>\n\n");
        self.output.push_str(RUNTIME);
        for stmt in &program.statements {
            match stmt {
                Stmt::Make { name, params, body, .. } => { self.functions.insert(name.clone(), (params.clone(), body.clone())); }
                Stmt::StructDef { name, fields, .. } => { self.structs.insert(name.clone(), fields.clone()); }
                _ => {}
            }
        }
        for (name, fields) in &self.structs {
            self.output.push_str("typedef struct {\n");
            for field in fields { self.output.push_str(&format!("    double {};\n", field)); }
            self.output.push_str(&format!("}} {};\n\n", name));
        }
        let functions: Vec<_> = self.functions.iter().map(|(n, (p, b))| (n.clone(), p.clone(), b.clone())).collect();
        for (name, params, body) in functions { self.gen_function(&name, &params, &body); }
        self.output.push_str("int main(void) {\n");
        for stmt in &program.statements {
            if !matches!(stmt, Stmt::Make { .. } | Stmt::StructDef { .. } | Stmt::Use { .. }) { self.gen_stmt(stmt, 1); }
        }
        self.output.push_str("    return 0;\n}\n");
        self.output.clone()
    }

    fn gen_function(&mut self, name: &str, params: &[String], body: &[Stmt]) {
        self.output.push_str(&format!("double sx_{}(", name));
        for (i, param) in params.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.output.push_str(&format!("double {}", param)); }
        self.output.push_str(") {\n");
        for stmt in body { self.gen_stmt(stmt, 1); }
        self.output.push_str("    return 0.0;\n}\n\n");
    }

    fn gen_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let ind = "    ".repeat(indent);
        match stmt {
            Stmt::Show(expr) => {
                let code = self.gen_expr(expr);
                if self.is_string_expr(expr) { self.output.push_str(&format!("{}printf(\"%s\\n\", {});\n", ind, code)); }
                else { self.output.push_str(&format!("{}printf(\"%g\\n\", {});\n", ind, code)); }
            }
            Stmt::Hold { name, value, .. } => self.gen_hold(&ind, name, value),
            Stmt::Assign { name, value } => self.output.push_str(&format!("{}{} = {};\n", ind, name, self.gen_expr(value))),
            Stmt::Give(expr) => self.output.push_str(&format!("{}return {};\n", ind, self.gen_expr(expr))),
            Stmt::When { condition, then_body, otherwise_body } => {
                self.output.push_str(&format!("{}if ({}) {{\n", ind, self.gen_expr(condition)));
                for stmt in then_body { self.gen_stmt(stmt, indent + 1); }
                self.output.push_str(&format!("{}}}", ind));
                if let Some(body) = otherwise_body { self.output.push_str(" else {\n"); for stmt in body { self.gen_stmt(stmt, indent + 1); } self.output.push_str(&format!("{}}}", ind)); }
                self.output.push('\n');
            }
            Stmt::While { condition, body } => {
                self.output.push_str(&format!("{}while ({}) {{\n", ind, self.gen_expr(condition)));
                for stmt in body { self.gen_stmt(stmt, indent + 1); }
                self.output.push_str(&format!("{}}}\n", ind));
            }
            Stmt::StructDef { .. } | Stmt::Make { .. } | Stmt::Use { .. } => {}
            Stmt::Expr(expr) => self.output.push_str(&format!("{}{};\n", ind, self.gen_expr(expr))),
        }
    }

    fn gen_hold(&mut self, ind: &str, name: &str, value: &Expr) {
        match value {
            Expr::String(s) => self.output.push_str(&format!("{}const char* {} = \"{}\";\n", ind, name, escape_c(s))),
            Expr::Array(elements) => {
                self.output.push_str(&format!("{}SxList {} = sx_list_new();\n", ind, name));
                for element in elements { self.output.push_str(&format!("{}sx_list_push(&{}, {});\n", ind, name, self.gen_expr(element))); }
            }
            Expr::StructLit { name: struct_name, fields } => {
                self.output.push_str(&format!("{}{} {} = {{", ind, struct_name, name));
                for (i, (_, value)) in fields.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.output.push_str(&self.gen_expr(value)); }
                self.output.push_str("};\n");
            }
            _ => {
                let code = self.gen_expr(value);
                if self.is_string_expr(value) { self.output.push_str(&format!("{}char* {} = {};\n", ind, name, code)); }
                else { self.output.push_str(&format!("{}double {} = {};\n", ind, name, code)); }
            }
        }
    }

    fn is_string_expr(&self, expr: &Expr) -> bool {
        match expr { Expr::String(_) => true, Expr::Call { name, .. } => matches!(name.as_str(), "concat" | "char_at" | "read_file" | "str" | "upper" | "lower" | "trim"), _ => false }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => n.to_string(), Expr::String(s) => format!("\"{}\"", escape_c(s)), Expr::Ident(name) => name.clone(),
            Expr::Binary { left, op, right } => {
                if *op == BinOp::Mod { format!("((double)((long)({}) % (long)({})))", self.gen_expr(left), self.gen_expr(right)) }
                else {
                    let operator = match op { BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*", BinOp::Div => "/", BinOp::Mod => "%", BinOp::Gt => ">", BinOp::Lt => "<", BinOp::Eq => "==", BinOp::Neq => "!=", BinOp::Gte => ">=", BinOp::Lte => "<=", };
                    format!("({} {} {})", self.gen_expr(left), operator, self.gen_expr(right))
                }
            }
            Expr::Call { name, args } => {
                let a: Vec<String> = args.iter().map(|x| self.gen_expr(x)).collect();
                match (name.as_str(), args.len()) {
                    ("len", 1) => self.gen_len(&args[0]), ("push", 2) => format!("(sx_list_push(&{}, {}), 0.0)", a[0], a[1]),
                    ("list_len", 1) => format!("((double)sx_list_len(&{}))", a[0]), ("list_get", 2) => format!("sx_list_get(&{}, (int)({}))", a[0], a[1]),
                    ("concat", 2) => format!("sx_concat({}, {})", a[0], a[1]), ("char_at", 2) => format!("sx_char_at({}, (int)({}))", a[0], a[1]),
                    ("contains", 2) => format!("sx_contains({}, {})", a[0], a[1]), ("starts_with", 2) => format!("sx_starts_with({}, {})", a[0], a[1]),
                    ("ends_with", 2) => format!("sx_ends_with({}, {})", a[0], a[1]), ("upper", 1) => format!("sx_upper({})", a[0]),
                    ("lower", 1) => format!("sx_lower({})", a[0]), ("trim", 1) => format!("sx_trim({})", a[0]),
                    ("read_file", 1) => format!("sx_read_file({})", a[0]), ("write_file", 2) => format!("sx_write_file({}, {})", a[0], a[1]),
                    ("str", 1) => format!("sx_str({})", a[0]), _ if stdlib::is_builtin(name) => format!("sx_{}({})", name, a.join(", ")), _ => format!("sx_{}({})", name, a.join(", ")),
                }
            }
            Expr::Array(elements) => { let values: Vec<String> = elements.iter().map(|x| self.gen_expr(x)).collect(); if values.is_empty() { "sx_list_new()".into() } else { format!("((SxList){{(double[]){{{}}}, {}, {}}})", values.join(", "), values.len(), values.len()) } }
            Expr::Index { array, index } => format!("sx_list_get(&{}, (int)({}))", self.gen_expr(array), self.gen_expr(index)),
            Expr::StructLit { name, fields } => { let values: Vec<String> = fields.iter().map(|(_, v)| self.gen_expr(v)).collect(); format!("({}){{{}}}", name, values.join(", ")) }
            Expr::Field { object, field } => format!("{}.{}", self.gen_expr(object), field),
        }
    }

    fn gen_len(&self, expr: &Expr) -> String {
        match expr { Expr::String(s) => s.chars().count().to_string(), Expr::Array(elements) => elements.len().to_string(), Expr::Ident(id) => format!("((double)sx_list_len(&{}))", id), other => format!("((double)strlen({}))", self.gen_expr(other)) }
    }
}

const RUNTIME: &str = r#"typedef struct { double *data; int len; int cap; } SxList;
static SxList sx_list_new(void) { SxList l = {NULL, 0, 0}; return l; }
static void sx_fail(const char *message) { fprintf(stderr, "Sayanox runtime error: %s\n", message); exit(1); }
static void sx_list_push(SxList *l, double v) { if (l->len >= l->cap) { int n = l->cap == 0 ? 8 : l->cap * 2; double *p = (double*)realloc(l->data, sizeof(double) * n); if (!p) sx_fail("out of memory"); l->data = p; l->cap = n; } l->data[l->len++] = v; }
static double sx_list_get(SxList *l, int i) { if (i < 0 || i >= l->len) sx_fail("list index out of bounds"); return l->data[i]; }
static int sx_list_len(SxList *l) { return l->len; }
static char *sx_char_at(const char *s, int i) { if (i < 0) sx_fail("string index out of bounds"); size_t n = strlen(s); if ((size_t)i >= n) sx_fail("string index out of bounds"); char *r=(char*)malloc(2); if(!r) sx_fail("out of memory"); r[0]=s[i]; r[1]=0; return r; }
static char *sx_concat(const char *a, const char *b) { size_t la=strlen(a), lb=strlen(b); char *r=(char*)malloc(la+lb+1); if(!r) sx_fail("out of memory"); memcpy(r,a,la); memcpy(r+la,b,lb); r[la+lb]=0; return r; }
static double sx_contains(const char *a, const char *b) { return strstr(a,b) ? 1.0 : 0.0; }
static double sx_starts_with(const char *a, const char *b) { size_t n=strlen(b); return strncmp(a,b,n)==0 ? 1.0 : 0.0; }
static double sx_ends_with(const char *a, const char *b) { size_t la=strlen(a), lb=strlen(b); return lb<=la && strcmp(a+la-lb,b)==0 ? 1.0 : 0.0; }
static char *sx_transform(const char *s, int mode) { size_t n=strlen(s); char *r=(char*)malloc(n+1); if(!r) sx_fail("out of memory"); for(size_t i=0;i<n;i++){ unsigned char c=(unsigned char)s[i]; r[i]=(char)(mode==1?toupper(c):tolower(c)); } r[n]=0; return r; }
static char *sx_upper(const char *s) { return sx_transform(s,1); }
static char *sx_lower(const char *s) { return sx_transform(s,2); }
static char *sx_trim(const char *s) { const unsigned char *a=(const unsigned char*)s; while(*a && isspace(*a)) a++; const unsigned char *b=a+strlen((const char*)a); while(b>a && isspace(b[-1])) b--; size_t n=(size_t)(b-a); char *r=(char*)malloc(n+1); if(!r) sx_fail("out of memory"); memcpy(r,a,n); r[n]=0; return r; }
static char *sx_read_file(const char *path) { FILE *f=fopen(path,"rb"); if(!f){fprintf(stderr,"Sayanox: cannot open %s\n",path); exit(1);} if(fseek(f,0,SEEK_END)!=0) sx_fail("file seek failed"); long n=ftell(f); if(n<0) sx_fail("file size failed"); rewind(f); char *buf=(char*)malloc((size_t)n+1); if(!buf) sx_fail("out of memory"); size_t got=fread(buf,1,(size_t)n,f); if(ferror(f)) sx_fail("file read failed"); buf[got]=0; fclose(f); return buf; }
static double sx_write_file(const char *path, const char *data) { FILE *f=fopen(path,"wb"); if(!f){fprintf(stderr,"Sayanox: cannot write %s\n",path); exit(1);} if(fputs(data,f)==EOF) sx_fail("file write failed"); fclose(f); return 0.0; }
static char *sx_str(double n) { char *buf=(char*)malloc(64); if(!buf) sx_fail("out of memory"); snprintf(buf,64,"%g",n); return buf; }
"#;

fn escape_c(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r").replace('\t', "\\t")
}
